apiVersion: v1
kind: Service
metadata:
  name: mongo-restaurant-db-service # This name is used as the host in the ConfigMap
  labels:
    app: mongo-restaurant-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-restaurant-db
  type: ClusterIP # Internal service only
